// Code generated by SdkContractGenerator. DO NOT EDIT.

export const contract = {
  "image-to-video": {
    "models": [
      "hailuo-02-image-to-video-pro",
      "hailuo-02-image-to-video-standard",
      "hailuo-2.3-image-to-video-pro",
      "hailuo-2.3-image-to-video-standard"
    ],
    "fields_by_model": {
      "hailuo-02-image-to-video-pro": {
        "duration_seconds": {
          "type": "integer"
        },
        "first_frame_image_url": {
          "required": true
        }
      },
      "hailuo-02-image-to-video-standard": {
        "duration_seconds": {
          "enum": [
            6,
            10
          ],
          "type": "integer"
        },
        "first_frame_image_url": {
          "required": true
        },
        "output_resolution": {
          "enum": [
            "512p",
            "768p"
          ]
        }
      },
      "hailuo-2.3-image-to-video-pro": {
        "duration_seconds": {
          "enum": [
            6,
            10
          ],
          "type": "integer"
        },
        "first_frame_image_url": {
          "required": true
        },
        "output_resolution": {
          "enum": [
            "768p",
            "1080p"
          ]
        }
      },
      "hailuo-2.3-image-to-video-standard": {
        "duration_seconds": {
          "enum": [
            6,
            10
          ],
          "type": "integer"
        },
        "first_frame_image_url": {
          "required": true
        },
        "output_resolution": {
          "enum": [
            "768p",
            "1080p"
          ]
        }
      }
    }
  },
  "text-to-video": {
    "models": [
      "hailuo-02-text-to-video-pro",
      "hailuo-02-text-to-video-standard"
    ],
    "fields_by_model": {
      "hailuo-02-text-to-video-pro": {
        "duration_seconds": {
          "type": "integer"
        }
      },
      "hailuo-02-text-to-video-standard": {
        "duration_seconds": {
          "enum": [
            6,
            10
          ],
          "type": "integer"
        }
      }
    }
  }
} as const;
